# Bulk delete admins from Canvas accounts 

import requests
import json
import csv
import operator
import urllib
import time
timestr = time.strftime("%Y-%m-%d")

from secure import oauth_token
# oauth_token is the oauth token from Canvas generated by a user with privileges for the courses

data = []
counter = 0

with open('account_admins_to_delete.csv', 'rb') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
    # loop over each row in the spreadsheet [account_id, user_id, role_id]
        account_id = row[0]
        user_id= row[1] # canvas_user_id
        role_id = row[2] # role_id = 1 for Department Admin

        url = 'https://harvard.instructure.com/api/v1/accounts/%s/admins/%s?role_id=%s' % (str(account_id), str(user_id), str(role_id))
        # call the API and reaise exceptions as needed
        headers = {
            'Authorization': 'Bearer {}'.format(oauth_token),
        }

        try: 
            resp = requests.delete(url, headers=headers )
            resp.raise_for_status()
        except requests.exceptions.RequestException as e:
            print e
            raise

        data.append([user_id, account_id, role_id])
        counter = counter + 1
        print counter

    
# Writing the information from data to a CSV file
with open('account_admins_deleted_%s.csv' % str(timestr), 'wb') as f:
    writer = csv.writer(f)
    writer.writerows(data)
