# GET module items from a course from the Canvas API, given a spreadsheet with module ids
# Please note that this does not include support for pagination if there are more than 100 module items in a module

import requests
import json
import csv
import operator
#from course_list import course_list
from secure import oauth_token
# oauth_token is the oauth token from Canvas generated by a user with privileges for the courses

data = []
counter = 0

with open('modules.csv', 'rb') as csvfile:
    # spreadsheet created by get_modules.py
    reader = csv.reader(csvfile)
    for row in reader:
    # loop over each row in the spreadsheet (module in a course)
        course_id = row[0]
        module_id = row[1]

        url = 'https://harvard.instructure.com/api/v1/courses/%s/modules/%s/items?per_page=100' % (str(course_id), str(module_id))
        # call the API and reaise exceptions as needed
        headers = {
            'Authorization': 'Bearer {}'.format(oauth_token),
        }

        try: 
            resp = requests.get(url, headers=headers )
            resp.raise_for_status()
        except requests.exceptions.RequestException as e:
            print e
            raise

        # save json response as a list of objects
        api_response = resp.json()

        # go through each json object 
        for position in api_response:
            module_item_id = position.get('id')
            link = position.get('external_url')
            # position.get('id') will return none if there none
            # looking for all of the module ids
            data.append([course_id, module_id, module_item_id, link])
        counter = counter + 1
        print counter

    
# Writing the information from data to a CSV file
with open('module_items.csv', 'wb') as f:
    writer = csv.writer(f)
    writer.writerows(data)
