# Edit external tool items from a spreadsheet using the Canvas API, given a spreadsheet with the ids

import requests
import json
import csv
import operator
import urllib
import time
timestr = time.strftime("%Y-%m-%d")
#from course_list import course_list
from secure import oauth_token_exed
# oauth_token is the oauth token from Canvas generated by a user with privileges for the courses

#domain = 'https://harvard.instructure.com'
domain = 'https://harvard-catalog-courses.instructure.com'

data = []
counter = 0

with open('lti_updates.csv', 'rb') as csvfile:
    # spreadsheet created by get_modules.py
    reader = csv.reader(csvfile)
    for row in reader:
    # loop over each row in the spreadsheet (lti installation in a course)
        course_id = row[0]
        external_tool_id = row[1]
        link = urllib.quote_plus(row[2])
        url = '%s/api/v1/courses/%s/external_tools/%s?custom_fields[url]=%s' % (str(domain),str(course_id), str(external_tool_id), str(link))
        # call the API and reaise exceptions as needed
        headers = {
            'Authorization': 'Bearer {}'.format(oauth_token),
        }

        try: 
            resp = requests.put(url, headers=headers )
            resp.raise_for_status()
        except requests.exceptions.RequestException as e:
            print e
            print ''
            print ''
            #raise

        data.append([course_id, external_tool_id, link])
        counter = counter + 1
        print counter

    
# Writing the information from data to a CSV file
with open('lti_links_edited_%s.csv' % str(timestr), 'wb') as f:
    writer = csv.writer(f)
    writer.writerows(data)
